// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaN4exkKQpgK9H2VNE7YvX2YRN05bK5ls',
    appId: '1:54601740273:web:683e573c271d045ebd5e50',
    messagingSenderId: '54601740273',
    projectId: 'shopify-97584',
    authDomain: 'shopify-97584.firebaseapp.com',
    storageBucket: 'shopify-97584.firebasestorage.app',
    measurementId: 'G-D91Y4L9KDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuV3vZEVXwJFfkVofNMq2zuiujwWCISS4',
    appId: '1:54601740273:android:e74725b151700cb6bd5e50',
    messagingSenderId: '54601740273',
    projectId: 'shopify-97584',
    storageBucket: 'shopify-97584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj8B1qdFnRtLIPEOEv9G8jMMdiDt2YchA',
    appId: '1:54601740273:ios:e46fa5c2956b1800bd5e50',
    messagingSenderId: '54601740273',
    projectId: 'shopify-97584',
    storageBucket: 'shopify-97584.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

}